repos:

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [
            --combine-as,
            --line-length=100,
            --ensure-newline-before-comments,
            --force-single-line-imports,
            --single-line-exclusions=typing,
            --trailing-comma,
            --multi-line=3,
            --lines-after-imports=2,
            --use-parentheses,
        ]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [
            --line-length=100,
        ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: forbid-new-submodules
      - id: fix-encoding-pragma
        args: [--remove]
      - id: end-of-file-fixer
        types_or: [python]
      - id: trailing-whitespace
        types_or: [python]
      - id: debug-statements
      - id: detect-private-key
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml

  -   repo: https://github.com/codespell-project/codespell
      rev: v2.2.2
      hooks:
        - id: codespell
          description: Checks for common misspellings.
          types_or: [python, markdown]
          exclude: "nautilus_trader/adapters/betfair/parsing.py"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        args: [
            --no-strict-optional,
            --ignore-missing-imports,
            --warn-no-return,
        ]
        additional_dependencies: []

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8 (python)
        additional_dependencies:
          - flake8-bandit
          - flake8-bugbear
          - flake8-coding
          - flake8-debugger
          - flake8-deprecated
          - flake8-pep3101
          - flake8-string-format
          - flake8-typing-imports
        types: [python]
        args: [
            --min-python-version=3.9.0,
            --max-complexity=10,
            --max-line-length=150,
            --statistics,
            --ignore=C101 E203 E252 E402 D100 D101 D102 S101 S403 W503,
        ]
