title                       : Deche  # The title of the book. Will be placed in the left navbar.
author                      : limx0  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer

repository:
  url: https://github.com/limx0/deche
  path_to_book: docs/
  branch: main  # Which branch of the repository should be used when creating links (optional)

execute:
  execute_notebooks: force

launch_buttons:
  thebe: true
  binderhub_url: "https://mybinder.org"

html:
  use_issues_button: true
  use_repository_button: true