name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - docs

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2

    # Install build dependencies
    - name: Install build dependencies
      run: python -m pip install --upgrade pip setuptools wheel poetry nox

    # Setup Poetry caching
    - name: Get Poetry cache dir
      id: poetry-cache
      run: echo "::set-output name=dir::$(poetry config cache-dir)"

    - name: Poetry/Nox cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.poetry-cache.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-test-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-poetry-test-
          ${{ runner.os }}-${{ matrix.python-version }}-poetry-

    # Install build dependencies
    - name: Install build dependencies
      run: poetry install
    # Build the book
    - name: Build the book
      run: |
        poetry run jupyter-book build deche

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html