name: pre-commit checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install build dependencies
        run: python -m pip install --upgrade pip setuptools poetry

      - uses: pre-commit/action@v2.0.0
