name: pre-commit checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      # Install mypy dependencies
      - name: Install mypy dependencies
        run: python3 -m pip install types-frozendict

      - uses: pre-commit/action@v2.0.0
